name: Build

on:
  push:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build-repo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install cookiecutter flake8 black
    - name: Generate Repository
      run: |
        cookiecutter . --no-input
        rm -Rf omero-somethingshort/.github/workflows/
    - name: Install Generated Repositority Dependencies
      run: |
        cd omero-somethingshort
        pip install -e .[all]
    - name: Check code
      run: |
        cd omero-somethingshort
        flake8 .
        black --check .
