name: Build

on:
  push:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build-repo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Run Cookiecutter
      uses: andrewthetechie/gha-cookiecutter@main
      with:
        # can be a link to a git repo or a local path
        template: .
    - name: Install Dependencies for checking code
      run: |
        pip install flake8 black
    - name: Check code
      run: |
        cd omero-somethingshort
        flake8 .
        black --check .
